services:
  - type: web
    name: book-garden-server
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/book-garden-server.jar"
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        fromSecret: mongodb_uri
      - key: SPRING_MAIL_USERNAME
        fromSecret: spring_mail_username
      - key: SPRING_MAIL_PASSWORD
        fromSecret: spring_mail_password
      - key: CLOUDINARY_CLOUD_NAME
        fromSecret: cloudinary_cloud_name
      - key: CLOUDINARY_API_KEY
        fromSecret: cloudinary_api_key
      - key: CLOUDINARY_API_SECRET
        fromSecret: cloudinary_api_secret
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        fromSecret: google_client_id
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        fromSecret: google_client_secret
      - key: GOOGLE_CLIENT_ID
        fromSecret: google_client_id
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: google_client_secret
      - key: GOOGLE_REDIRECT_URI
        value: https://garden-book-reactjs.web.app
      - key: GOOGLE_TOKEN_URI
        value: https://accounts.google.com/o/oauth2/token
